# Loading in the data

In [130]:
import pandas as pd
import numpy as np
import os, random, math, glob
from IPython.display import Image as IM
from IPython.display import clear_output
from matplotlib import pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = [16, 10]

In [131]:
df_train = pd.read_csv('Train.csv')
df = pd.read_csv('Test.csv')
df_train.head()

,ward,total_households,total_individuals,target,dw_00,dw_01,dw_02,dw_03,dw_04,dw_05,...,pw_03,pw_04,pw_05,pw_06,pw_07,pw_08,ADM4_PCODE,lat,lon,NL
0,41601001: Ward 1,1674.45058,5888.20750,16.773757,0.933841,0.000846,0.005490,0.000676,0.000000,0.001372,...,0.002848,0.007537,0.000000,0.012928,0,0,ZA4161001,-29.682270,24.734743,0.292039
1,41601002: Ward 2,1736.99230,6735.33812,21.496661,0.696940,0.001253,0.004402,0.000000,0.002301,0.001323,...,0.014566,0.057127,0.019092,0.004131,0,0,ZA4161002,-29.119311,24.757737,3.207775
2,41601003: Ward 3,2403.57591,7273.04995,10.931425,0.810545,0.004517,0.008891,0.003986,0.007735,0.000956,...,0.057560,0.010358,0.001421,0.040881,0,0,ZA4161003,-29.142276,25.094093,0.000000
3,41601004: Ward 4,1740.78737,5734.49046,23.119257,0.659914,0.000000,0.006129,0.000000,0.000813,0.037245,...,0.000000,0.000669,0.000000,0.005011,0,0,ZA4161004,-29.372052,24.942867,2.038778
4,41601005: Ward 5,1730.51451,6657.23835,13.652252,0.950575,0.000655,0.001473,0.000598,0.006999,0.000818,...,0.004859,0.001290,0.000673,0.017629,0,0,ZA4161005,-29.409381,25.290165,0.000000

In [132]:
df.shape

(1013, 62)

# Modeling

In [133]:
df_train = df_train.drop(['ADM4_PCODE', 'ward'], axis = 1)
df_test = df.drop(['ADM4_PCODE', 'ward'], axis = 1)

In [134]:
y = df_train['target']
df_train = df_train.drop('target', axis = 1)

In [135]:
data_dmatrix = xgb.DMatrix(data=df_train,label=y)

In [136]:
#from sklearn.model_selection import train_test_split

In [137]:
xg_reg = xgb.XGBRegressor(objective ='reg:squarederror')

In [138]:
xg_reg.fit(df_train,y)
preds = xg_reg.predict(df_test)

In [139]:
#rmse = np.sqrt(mean_squared_error(y_test, preds))
#print("RMSE: %f" % (rmse))

In [140]:
df

,ward,total_households,total_individuals,dw_00,dw_01,dw_02,dw_03,dw_04,dw_05,dw_06,...,pw_03,pw_04,pw_05,pw_06,pw_07,pw_08,ADM4_PCODE,lat,lon,NL
0,21001001: Ward 1,2504.95194,8745.15151,0.947257,0.000873,0.002021,0.000000,0.000000,0.030116,0.000452,...,0.001757,0.000000,0.000000,0.006649,0.0,0.0,ZA2101001,-32.637758,23.848688,0.000000
1,21001002: Ward 2,2080.27718,7258.11764,0.844993,0.000481,0.043629,0.004714,0.012323,0.012300,0.022132,...,0.000691,0.000000,0.000000,0.002916,0.0,0.0,ZA2101002,-31.990536,24.555818,0.000000
2,21001003: Ward 3,1106.62639,5919.13170,0.651380,0.007937,0.007113,0.000000,0.001977,0.259711,0.006505,...,0.002253,0.000000,0.000000,0.000000,0.0,0.0,ZA2101003,-32.283595,24.563940,8.269556
3,21001004: Ward 4,2175.56096,10280.57452,0.410837,0.002468,0.011511,0.000485,0.000000,0.449604,0.009256,...,0.000000,0.000661,0.000000,0.001379,0.0,0.0,ZA2101004,-32.261612,24.542202,8.626625
4,21001005: Ward 5,1270.83883,6018.34202,0.942851,0.002638,0.000821,0.000000,0.000891,0.000787,0.000830,...,0.000000,0.000000,0.000000,0.001660,0.0,0.0,ZA2101005,-32.251571,24.558537,8.601754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008,19100107: Ward 107,16076.89903,43296.51372,0.668295,0.002827,0.207749,0.028813,0.069741,0.010701,0.003941,...,0.000392,0.000291,0.000148,0.002277,0.0,0.0,ZA1910107,-33.806524,18.496094,33.913055
1009,19100108: Ward 108,17470.24004,53538.12816,0.483111,0.000824,0.001189,0.000870,0.000554,0.000370,0.001954,...,0.030744,0.008313,0.000348,0.022417,0.0,0.0,ZA1910108,-33.982120,18.673308,60.009486
1010,19100109: Ward 109,9467.25336,40332.11708,0.579036,0.007184,0.066458,0.001003,0.000371,0.150977,0.007699,...,0.003850,0.000990,0.000352,0.010670,0.0,0.0,ZA1910109,-34.062704,18.767457,35.834860
1011,19100110: Ward 110,6111.31195,27793.92916,0.623537,0.002216,0.101188,0.001517,0.000939,0.158979,0.013516,...,0.000559,0.000000,0.000204,0.026741,0.0,0.0,ZA1910110,-34.057772,18.487893,50.153301
1012,19100111: Ward 111,9746.91152,37494.86375,0.689628,0.002557,0.010899,0.001380,0.001674,0.031751,0.008765,...,0.047527,0.000783,0.004717,0.010252,0.0,0.0,ZA1910111,-33.850503,18.721961,43.626138

In [141]:
df['preds'] = xg_reg.predict(df_test)

In [142]:
df[['ward', 'preds']].to_csv('predictions.csv', index=False)

In [144]:
df[['ward', 'preds']]

                    ward      preds
0       21001001: Ward 1  17.666430
1       21001002: Ward 2  15.072925
2       21001003: Ward 3  20.739376
3       21001004: Ward 4  17.038681
4       21001005: Ward 5  20.164087
...                  ...        ...
1008  19100107: Ward 107   6.447568
1009  19100108: Ward 108  21.770216
1010  19100109: Ward 109  17.875971
1011  19100110: Ward 110  13.953951
1012  19100111: Ward 111  16.512848

[1013 rows x 2 columns]